[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200

[[redirects]]
  from = "/api/session"
  to = "/.netlify/functions/session"
  status = 200

[[headers]]
  for = "/songs/*"
  [headers.values]
    Access-Control-Allow-Origin = "*" 